mfbc_dockerfile_path: "{{ pfbc_dockerfile_path }}"
mfbc_extracted_fbc_location: "{{ pfbc_extracted_fbc_location }}"
mfbc_multi_arch_output_image: ""
mfbc_list_architectures_from: "quay.io/operator-framework/opm:{{ opm_version }}"
container_push_extra: ""
pfbc_extracted_fbc_location: "/tmp/fbc_extracted"
mfbc_multi_arch_output_image_dev_temp_human_readable_tag: "fbc"
mfbc_multi_arch_output_image_dev_temp_human_readable_enabled: true
